### ISSUE TITLE
[Bug]: Fehler beim Starten des Clients

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#158]
### What happened?

Irgendein Fehler kommt immer beim Starten des Clients

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.SerializersKt__SerializersKt.serializer, parameter type
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.api.value.ListValue.serialize(ListValue.kt:50)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.config.profile.Profile.save(Profile.kt:48)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.api.NoRiskClientUi.addEntries(NoRiskClientUi.kt:31)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.test.TestModules.init(createTestHud.kt:111)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.ManagerKt.init$lambda$0(Manager.kt:42)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.handler$zlp000$fabric-lifecycle-events-v1$onStart(MinecraftClient.java:5788)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:870)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:265)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:43:42] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by SleepyPxnda** [comment]
Fixed
