### ISSUE TITLE
FEATURE-REQUEST]: Generic Listen oder nur String? serializen

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#167]
### Your idea

```[21:47:43] [Render thread/INFO] (noriskclient-ui) Saving Profile Default...
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.SerializersKt__SerializersKt.serializer, parameter type
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.api.value.ListValue.serialize(ListValue.kt:50)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.config.profile.Profile.save(Profile.kt:48)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.api.NoRiskClientUi.addEntries(NoRiskClientUi.kt:31)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.test.TestModules.init(createTestHud.kt:111)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at gg.norisk.ui.ManagerKt.init$lambda$0(Manager.kt:42)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.handler$zic000$fabric-lifecycle-events-v1$onStart(MinecraftClient.java:5288)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:870)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:265)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:47:43] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)```



### Linked issues

_No response_

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Ich habe damals für das Knife Animation Module einen neuen Listen Typ geaddet... aber leider nicht generic und string only, könntet ihr mal checken wieso der error auftritt? Vielen dank!

**Comment by SleepyPxnda** [comment]
Ist das noch wichtig ?

**Comment by SleepyPxnda** [comment]
@copyandexecute passiert hier noch was oder können wir das zumachen ?

**Comment by TimLohrer** [comment]
Kp was das ist aber is uralt, reopen, wenn wichtig.
