### ISSUE TITLE
[Bug]:  Replaymod Custom button geht nicht!

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#251]
### What happened?

Wenn ich versuche auf den Custom Butten zu klicken (hoffe ihr checkt was ich meine) Werde ich entwerder wieder in den menu screen gekickt, oder mein game crashed. Manchmal bekomme ich auch Logs von der Replay Mod. Wenn ich neben Copy Logs auf Back klicke, crashed mein game auch... Habe alles mögliche versucht, muss ein client bug sein.. Also Pc restarted, Mod neu installiert, neues Replay aufgenommen. 

Repaly Mod Logs: ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-07-08 17:11:44
Description: Opening replay

com.replaymod.core.files.ReplayFilesService$FileLockedException: C:\Users\Hapix\AppData\Roaming\norisk\NoRiskClient\data\gameDir\norisk-dev\replay_recordings\2024_07_08_16_43_19.mcpr
	at com.replaymod.core.files.ReplayFilesService.open(ReplayFilesService.java:42)
	at com.replaymod.core.files.ReplayFilesService.open(ReplayFilesService.java:34)
	at com.replaymod.render.gui.GuiRenderQueue.processMultipleReplays(GuiRenderQueue.java:220)
	at gg.norisk.replay.utils.ReplayUtils.renderPerspectives(ReplayUtils.kt:65)
	at gg.norisk.replay.ui.components.ReplayListComponent._init_$lambda$4(ReplayListComponent.kt:63)
	at io.wispforest.owo.ui.component.ButtonComponent.lambda$new$0(ButtonComponent.java:36)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at io.wispforest.owo.ui.component.VanillaWidgetComponent.onMouseDown(VanillaWidgetComponent.java:134)
	at net.minecraft.class_339.onMouseDown(class_339.java:1149)
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:154)
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:154)
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
	at io.wispforest.owo.ui.core.OwoUIAdapter.method_25402(OwoUIAdapter.java:218)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 280984272 bytes (267 MiB) / 905969664 bytes (864 MiB) up to 7147094016 bytes (6816 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700KF
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5244
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25971.87
	Virtual memory used (MB): 13419.41
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 839.39
	JVM Flags: 8 total; -Xmx6812M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		ai-replaymod: AI ReplayMod 1.20.4-1.0.1
		emojiful: Emojiful 5.0.2
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.17
			midnightlib: MidnightLib 1.1.0
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 6.0.3
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.12.1
		mcreal: McReal 1.20.4-2.0.2
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		noriskclient: NoRisk Client 1.20.4-2.0.3
		noriskclient-branding: NoRiskClient Branding 1.20.4-2.0.2
		noriskclient-clearbackground: NoRiskClient ClearBackground 1.20.4-2.0.0
		noriskclient-cosmetics: NoRiskClient Cosmetics 1.20.4-2.0.8
			mm: Manningham Mills 2.3
		noriskclient-discordintegration: NoRiskClient Discord 1.20.4-2.0.0
			com_github_caoimhebyrne_kdiscordipc: KDiscordIPC 384357c3f1
			com_kohlschutter_junixsocket_junixsocket-common: junixsocket-common 2.5.0
			com_kohlschutter_junixsocket_junixsocket-native-common: junixsocket-native-common 2.5.0
			org_slf4j_slf4j-api: slf4j-api 1.7.36
		noriskclient-fabric-utils: NoRiskClient Fabric Utils 1.20.4-2.1.1
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			com_google_errorprone_error_prone_annotations: error_prone_annotations 2.21.1
			com_squareup_okhttp3_okhttp: okhttp 4.10.0
			com_squareup_okio_okio-jvm: okio-jvm 3.0.0
			commons-codec_commons-codec: commons-codec 1.15
			gg_norisk_backend-base-api: backend-base-api 1.2.6
			io_ktor_ktor-client-cio-jvm: ktor-client-cio-jvm 2.3.1
			io_ktor_ktor-client-content-negotiation-jvm: ktor-client-content-negotiation-jvm 2.3.1
			io_ktor_ktor-client-core-jvm: ktor-client-core-jvm 2.3.1
			io_ktor_ktor-events-jvm: ktor-events-jvm 2.3.1
			io_ktor_ktor-http-cio-jvm: ktor-http-cio-jvm 2.3.1
			io_ktor_ktor-http-jvm: ktor-http-jvm 2.3.1
			io_ktor_ktor-io-jvm: ktor-io-jvm 2.3.1
			io_ktor_ktor-network-jvm: ktor-network-jvm 2.3.1
			io_ktor_ktor-network-tls-jvm: ktor-network-tls-jvm 2.3.1
			io_ktor_ktor-serialization-jvm: ktor-serialization-jvm 2.3.1
			io_ktor_ktor-serialization-kotlinx-json-jvm: ktor-serialization-kotlinx-json-jvm 2.3.1
			io_ktor_ktor-serialization-kotlinx-jvm: ktor-serialization-kotlinx-jvm 2.3.1
			io_ktor_ktor-utils-jvm: ktor-utils-jvm 2.3.1
			io_ktor_ktor-websocket-serialization-jvm: ktor-websocket-serialization-jvm 2.3.1
			io_ktor_ktor-websockets-jvm: ktor-websockets-jvm 2.3.1
			org_checkerframework_checker-qual: checker-qual 3.37.0
		noriskclient-freelook: NoRiskClient Freelook 1.20.4-2.0.0
		noriskclient-fullbright: NoRiskClient Fullbright 1.20.4-2.0.0
		noriskclient-nametags: NoRiskClient NameTags 1.20.4-2.0.0
		noriskclient-nofog: NoRiskClient NoFog 1.20.4-2.0.0
		noriskclient-screenshot: NoRiskClient Screenshot 1.20.4-2.0.1
		noriskclient-toasts: NoRiskClient Toasts 1.20.4-2.0.2
		noriskclient-ui: NoRiskClient UI 1.20.4-2.0.4
			owo: oÏ‰o 0.12.1-SNAPSHOT
				blue_endless_jankson: jankson 1.2.2
		noriskclient-zoom: NoRiskClient Zoom 1.20.4-2.0.0
		nrcfriends: NoRisk Friends 1.20.4-2.2.8
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.5
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.5
			io_jsonwebtoken_jjwt-orgjson: jjwt-orgjson 0.12.5
			org_json_json: json 20231013
		nrcminigames: NoRisk Minigames 1.20.4-2.0.0
		nvidium: Nvidium 0.2.6-beta
		player-animator: Player Animator 1.0.2-rc1+1.20
		recursiveresources: Recursive Resources 2.5.2+1.20.4
			cicada: CICADA 0.5.2+1.20.2-plus
			shared-resources-api: Shared Resources API 1.5.2
		replaymod: Replay Mod 1.20.4-2.6.15
		satin: Satin 1.16.0
		silk-all: Silk (All modules) 1.10.3
			silk-commands: Silk Commands 1.10.3
			silk-core: Silk Core 1.10.3
			silk-game: Silk Game 1.10.3
			silk-igui: Silk Inventory GUI 1.10.3
			silk-nbt: Silk NBT 1.10.3
			silk-network: Silk Network 1.10.3
			silk-persistence: Silk Persistence 1.10.3
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.8+mc1.20.4
		subwaysurfers: SubwaySurfers 1.20.4-1.4.0
			gg_norisk_subwaysurfers-api: subwaysurfers-api 1.0.0
	Loaded Shaderpack: (off)

### How to reproduce ?

1. Nehme ein Replay auf
2. Folge den schritten im video

https://github.com/NoRiskClient/issues/assets/165488563/bcc00ed3-ee65-4c6d-ad74-6ca6f432ecbf

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/wvuw57t
```

**Comment by SirKnubble** [comment]
![Bild_2024-07-20_055036396](https://github.com/user-attachments/assets/5ba056f9-0fdf-46cf-b782-666d2a882921)
(einfach random Fehler den ich auch mal festhalten wollte, einfach nochmal öffnen hat geklappt.)
<hr/>

Ich glaube, weil die File Adminzugang benötigt.
NRC nicht als Admin starten hat einfach nichts gemacht, Log:
<details><summary>Log</summary>
<p>

[20-07-2024 05:52:13] INFO - [05:52:13] [Render thread/INFO]: [STDERR]: java.io.IOException: Unknown I/O error listing contents of directory: C:\Users\PDHAY\AppData\Local\Temp\15287698583651422924

[20-07-2024 05:52:13] INFO - [05:52:13] [Render thread/INFO]: [STDERR]:         at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2190)
[05:52:13] [Render thread/INFO]: [STDERR]:      at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:333)
[05:52:13] [Render thread/INFO]: [STDERR]:      at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
[05:52:13] [Render thread/INFO]: [STDERR]:      at com.replaymod.replay.FullReplaySender.terminateReplay(FullReplaySender.java:387)
[05:52:13] [Render thread/INFO]: [STDERR]:      at com.replaymod.replay.ReplayHandler.endReplay(ReplayHandler.java:233)
[05:52:13] [Render thread/INFO]: [STDERR]:      at com.replaymod.render.gui.GuiRenderQueue.lambda$processMultipleReplays$13(GuiRenderQueue.java:251)
[05:52:13] [Render thread/INFO]: [STDERR]:      at com.replaymod.render.gui.GuiRenderQueue.processQueue(GuiRenderQueue.java:201)
[05:52:13] [Render thread/INFO]: [STDERR]:      at com.replaymod.render.gui.GuiRenderQueue.processMultipleReplays(GuiRenderQueue.java:249)
[05:52:13] [Render thread/I
[20-07-2024 05:52:13] INFO - NFO]: [STDERR]:    at gg.norisk.replay.utils.ReplayUtils.renderPerspectives(ReplayUtils.kt:66)
[05:52:13] [Render thread/INFO]: [STDERR]:      at gg.norisk.replay.ui.components.ReplayListComponent._init_$lambda$4(ReplayListComponent.kt:63)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.component.ButtonComponent.lambda$new$0(ButtonComponent.java:36)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_4185.method_25306(class_4185.java:95)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_4264.method_25348(class_4264.java:48)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_339.method_25402(class_339.java:145)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.component.VanillaWidgetComponent.onMouseDown(VanillaWidgetComponent.java:134)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_339.onMouseDown(class_339.java:1149)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.core.ParentCompone
[20-07-2024 05:52:13] INFO - nt.onMouseDown(ParentComponent.java:154)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:154)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
[05:52:13] [Render thread/INFO]: [STDERR]:      at io.wispforest.owo.ui.core.OwoUIAdapter.method_25402(OwoUIAdapter.java:218)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_4069.method_25402(class_4069.java:38)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_312.method_1611(class_312.java:99)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_437.method_25412(class_437.java:414)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_312.method_1601(class_312.java:99)
[05:52:13] [Render thread/INFO]: [STDERR]:
[20-07-2024 05:52:13] INFO -    at net.minecraft.class_312.method_22686(class_312.java:180)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_1255.execute(class_1255.java:102)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_312.method_22684(class_312.java:180)
[05:52:13] [Render thread/INFO]: [STDERR]:      at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[05:52:13] [Render thread/INFO]: [STDERR]:      at org.lwjgl.system.JNI.invokeV(Native Method)
[05:52:13] [Render thread/INFO]: [STDERR]:      at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[05:52:13] [Render thread/INFO]: [STDERR]:      at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_310.method_1523(class_310.java:1352)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.class_310.method_1514(class_310.java:888)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.minecraft.client.main.Main.main(Main.j
[20-07-2024 05:52:13] INFO - ava:265)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[05:52:13] [Render thread/INFO]: [STDERR]:      at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

</p>
</details> 

NRC als Admin starten hat mir den gleichen error gegeben.

**Comment by SirKnubble** [comment]
tbc
