### ISSUE TITLE
[Bug]: Error MC Real

### ISSUE THREAD

**Issue by Rotstein007** [NoRiskClient/issues#376]
### How to reproduce ?

Wenn man auf das Kommentar Symbol bei einem Bild in MC Real clickt, dann stürtzt Minecraft mit folgendem log ab:
![Bildschirmfoto vom 2024-09-02 17-29-07](https://github.com/user-attachments/assets/e7627731-e065-4ffa-841e-b184aef1a9c5)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
[17:25:40] [DefaultDispatcher-worker-25/ERROR]: You need to post an McReal before viewing content from others.
[17:25:44] [DefaultDispatcher-worker-16/INFO]: Requesting Player Progress for RadFlunder
[17:25:46] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.mixinextras$bridge$method_15998$288(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.wrapOperation$boh000$mcreal$maybeSwapBuffers(class_310.java:9161) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property commentBox has not been initialized
	at gg.norisk.mcreal.ui.components.PostComponent.commentPost(PostComponent.kt:281) ~[NoRiskClient-McReal.jar:?]
	at gg.norisk.mcreal.ui.components.PostComponent.access$commentPost(PostComponent.kt:40) ~[NoRiskClient-McReal.jar:?]
	at gg.norisk.mcreal.ui.components.PostComponent$initEmojis$commentIcon$1.invoke(PostComponent.kt:287) ~[NoRiskClient-McReal.jar:?]
	at gg.norisk.mcreal.ui.components.PostComponent$initEmojis$commentIcon$1.invoke(PostComponent.kt:286) ~[NoRiskClient-McReal.jar:?]
	at gg.norisk.ui.components.IconButtonComponent.onMouseDown(IconButtonComponent.kt:85) ~[NoRiskClient-UI.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.container.ScrollContainer.onMouseDown(ScrollContainer.java:205) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib.jar:?]
	at io.wispforest.owo.ui.core.OwoUIAdapter.method_25402(OwoUIAdapter.java:218) ~[owo-lib.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 18 more
[17:25:46] [Render thread/INFO]: Stopping worker threads
```

**Comment by copyandexecute** [comment]
Sollte jetzt fixed sein oder?

**Comment by Rotstein007** [comment]
Schau gleich mal nach

**Comment by Rotstein007** [comment]
Sorry dass das so lange gedaurt hat. Ja das Problem wurde behoben : )
