### ISSUE TITLE
[Bug]: Emote Lib Crash, hand rendering

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#382]
### How to reproduce ?

Map in die Hand nehmen und boom

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
[11:49:05] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ClassCastException: class me.x150.geckoAnimLib.core.ReplacedPlayerRenderer cannot be cast to class net.minecraft.class_1007 (me.x150.geckoAnimLib.core.ReplacedPlayerRenderer and net.minecraft.class_1007 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @548a9f61)
	at net.minecraft.class_759.method_3216(class_759.java:177) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3231(class_759.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3228(class_759.java:487) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_22976(class_759.java:399) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$bcn000$iris$disableVanillaHandRendering(class_757.java:4021) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3172(class_757.java:790) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1114) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
[11:49:05] [Server thread/INFO]: Trying to Close Open To Lan Server
```

**Comment by 0x3C50** [comment]
![image](https://github.com/user-attachments/assets/5ddc8675-bf15-441f-8fc2-6ef70957518e)

**Comment by 0x3C50** [comment]
c3caf092

**Comment by copyandexecute** [comment]
https://github.com/NoRiskClient/noriskclient-client-modules/commit/c3caf0924bfb4d640f09125c4163626568668dde
