### ISSUE TITLE
[Bug]: Insane ram usage on mac

### ISSUE THREAD

**Issue by enricoxD** [NoRiskClient/issues#394]
### How to reproduce ?

- Starte noriskclient auf mac
- Welt betreten
- Rumfliegen oder so

Ingame wird zwar nur eine niedrige RAM-Auslastung angezeigt, das spielt freezed aber alle paar Sekunden. Im Activity Monitor wird eine deutliche höhere Auslastung angezeigt? 

![grafik](https://github.com/user-attachments/assets/75ff0a9e-f5d2-4a36-b811-91ccef5fbd65)
![ram](https://github.com/user-attachments/assets/97902c60-9857-455f-b077-9e416c19f944)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
Der log wird (fast ausschließlich) mit dem vollgespammt, ka ob das echt relevant ist:

[12:36:33] [Render thread/ERROR]: Failed to load shader
net.irisshaders.iris.helpers.FakeChainedJsonException: Invalid shaders/program/motion_blur.json (noriskclient): 
	at net.minecraft.class_2973.handler$bag000$iris$changeShaderParseException(class_2973.java:516) ~[client-intermediary.jar:?]
	at net.minecraft.class_2973.method_12856(class_2973.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_280.<init>(class_280.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_283.<init>(class_283.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1262(class_279.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1257(class_279.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1256(class_279.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
	at gg.norisk.client.module.modules.MotionBlur$1.invoke(MotionBlur.kt:40) [NoRiskClient-Client.jar:?]
	at gg.norisk.client.module.modules.MotionBlur$1.invoke(MotionBlur.kt:33) [NoRiskClient-Client.jar:?]
	at gg.norisk.ui.api.module.Module$subscribe$1.invoke(Module.kt:68) [NoRiskClient-UI.jar:?]
	at gg.norisk.ui.api.module.Module$subscribe$1.invoke(Module.kt:63) [NoRiskClient-UI.jar:?]
	at net.silkmc.silk.core.event.Event.invoke(Event.kt:83) [silk-core-1.10.7-bd65c9a7469083c.jar:?]
	at net.minecraft.class_757.handler$cbf000$noriskclient$hookGameRenderAfter(class_757.java:4610) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:953) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: net.irisshaders.iris.gl.shader.ShaderCompileException: noriskclient:motion_blur.fsh: noriskclient:motion_blur.fsh: ERROR: 0:1: '' :  version '120' is not supported
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:6: 'varying' : syntax error: syntax error

	at net.minecraft.class_281.handler$bbo000$iris$causeException(class_281.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_34416(class_281.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_5937.method_34415(class_5937.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_280.method_16036(class_280.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_280.<init>(class_280.java:137) ~[client-intermediary.jar:?]
	... 18 more
```

**Comment by MeisterAH** [comment]
ist nur bei apple silicon chips so 👀

**Comment by TimLohrer** [comment]
@enricoxD das is n memory leak :/
Der Virtual Memory Wert steigt nur, aber sinkt nt mal wenn ich ins main menu gehe...
aber tbh kp wo der herkommt
https://cdn.discordapp.com/attachments/1252973534112907295/1286346805113782272/Bildschirmfoto_2024-09-19_um_17.22.44.png?ex=66ed9351&is=66ec41d1&hm=e5e99143f33a9828a3aca5abf60b0247e1b9ed4fad1a3aec8a4e1c751c0404a5&

**Comment by copyandexecute** [comment]
Ohje das hab ich actually heute auch bemerkt

**Comment by copyandexecute** [comment]
ich versuchs

**Comment by copyandexecute** [comment]
Wir bauen den Launcher aktuell als Intel, dann kommt Rosetta ins Spiel und es wird ein falscher Prozessor Type angezeigt
dadurch falsche jdk -> lags

**Comment by copyandexecute** [comment]
Fix: https://github.com/NoRiskClient/noriskclient-launcher/commit/5c307c76bcd71c38994d7324798f5bcd8159e798

**Comment by copyandexecute** [comment]
@MeisterAH meld dich mal ob dir alles geht auf discord

**Comment by copyandexecute** [comment]
Kannst du mir sagen wer?

**Comment by enricoxD** [comment]
https://discord.com/channels/774271756549619722/1095740246802579487/1305958516980318248 @copyandexecute

**Comment by copyandexecute** [comment]
Hat er Silicon, hatte er noriskclient davor, hat er runtimes gelöscht?

**Comment by BigBrainRobin29** [comment]
Er hat nen M1, wie er im Discord gesagt hat.

> das meory leak wie vor 2 monaten (auch vom dc)
Wahrscheinlich hatte er ihn schon davor und das Problem auch.

**Comment by MeisterAH** [comment]
> Hat er Silicon, hatte er noriskclient davor, hat er runtimes gelöscht?

hab ihm grad gesagt das er runtime löschen soll und anscheinend laggt es bei ihm nicht mehr so, aber der memory leak ist immer noch da (https://discord.com/channels/774271756549619722/1313169358293303428/1313520389078515712)

**Comment by brentspine** [comment]
Still happening, I am closing the Ticket related to this (2550) after a month of activity. Will update if there is any more information, but definitely not fixed

**Comment by brentspine** [comment]
<img width="700" height="812" alt="Image" src="https://github.com/user-attachments/assets/06a8eeab-1120-41b0-95df-00e622d26095" />

**Comment by copyandexecute** [comment]
Thanks for reporting this! We're moving all issue tracking to https://norisk.gg/issues and will be closing GitHub issues soon. Please re-open your report on the new tracker so we don't lose it — see you there! 💙
