### ISSUE TITLE
[Bug]: Emote Lib Crash X Bedrock Particle X First Person

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#401]
### How to reproduce ?

1. Minecraft Starten
2. Welt joinen
3. DIREKT `/emote animation "aang:emotes/air_scooter.animation.json"` ausführen

Wichtig!
Wenn man vorher F5 geht, geht es
Wenn man vorher NICHT F5 geht, crash

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
java.lang.NullPointerException: Cannot read field "x" because "relPos" is null
	at gg.norisk.emote.keyframe.EmoteParticleKeyframeHandler.handle(EmoteParticleKeyframeHandler.kt:42)
	at software.bernie.geckolib.animation.AnimationController.processCurrentAnimation(AnimationController.java:630)
	at software.bernie.geckolib.animation.AnimationController.process(AnimationController.java:469)
	at software.bernie.geckolib.animation.AnimationProcessor.tickAnimation(AnimationProcessor.java:88)
	at software.bernie.geckolib.model.GeoModel.handleAnimations(GeoModel.java:188)
	at me.x150.geckoAnimLib.core.ReplacedPlayerRenderer.actuallyRender(ReplacedPlayerRenderer.java:222)
	at me.x150.geckoAnimLib.core.ReplacedPlayerRenderer.justTickTheAnimationsDontActuallyRender(ReplacedPlayerRenderer.java:173)
	at net.minecraft.client.render.WorldRenderer.handler$zkk000$emote-lib$preRender(WorldRenderer.java:7215)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java)
	at net.minecraft.client.render.GameRenderer.mixinextras$bridge$render$236(GameRenderer.java)
	at net.minecraft.client.render.GameRenderer.wrapOperation$zfp000$noriskclient-fabric-utils$renderer_postWorldRender(GameRenderer.java:2746)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1258)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:1028)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1186)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:810)
	at net.minecraft.client.main.Main.main(Main.java:228)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by 0x3C50** [comment]
9fde8e3
