### ISSUE TITLE
[Bug]: thread 'tokio-runtime-worker' panicked at src/app/gui.rs:1298:89

### ISSUE THREAD

**Issue by onlyJakob** [NoRiskClient/issues#415]
### How to reproduce ?

1. delete all nrc related folders
2. compile nrc client from latest master
3. execute the resulting binary
4. thread panicked

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Linux

### Version (for launcher bugs)

v0.5.10/master

### Relevant log output

```shell
[02-10-2024 21:45:28] INFO - ###############################
[02-10-2024 21:45:28] INFO -
[02-10-2024 21:45:28] INFO -
[02-10-2024 21:45:28] INFO -       NEW LAUNCHER LOG
[02-10-2024 21:45:28] INFO -
[02-10-2024 21:45:28] INFO -
[02-10-2024 21:45:28] INFO - ###############################
[02-10-2024 21:45:28] INFO - Creating launcher directories...
[02-10-2024 21:45:28] INFO - Finish launcher directories...

** (no-risk-client:104223): WARNING **: 21:45:28.215: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
[02-10-2024 21:45:28] INFO - IsClientRunning is false
[02-10-2024 21:45:28] INFO - URL: https://api.norisk.gg/api/v1/core/online
[02-10-2024 21:45:28] ERROR - Default User Error: User is not logged in, no credentials available!
[02-10-2024 21:45:28] INFO - Storing Launcher Profiles...
[02-10-2024 21:45:28] INFO - Default User Was Updated.
[02-10-2024 21:45:28] INFO - URL: https://api.norisk.gg/api/v1/launcher/maintenance-mode
[02-10-2024 21:45:28] INFO - Storing Launcher Profiles...
[02-10-2024 21:45:28] DEBUG - starting new connection: https://api.norisk.gg/
[02-10-2024 21:45:28] DEBUG - starting new connection: https://api.norisk.gg/
[02-10-2024 21:45:29] INFO - Maintenance Mode: false
[02-10-2024 21:45:29] INFO - URL: https://api.norisk.gg/api/v1/launcher/online
[02-10-2024 21:45:29] INFO - Core API online state: true, Launcher API online state: true
[02-10-2024 21:45:29] INFO - API is online!
thread 'tokio-runtime-worker' panicked at src/app/gui.rs:1298:89:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[02-10-2024 21:45:29] DEBUG - starting new connection: https://api.norisk.gg/
[02-10-2024 21:45:30] INFO - Updater event: null UPTODATE
```

**Comment by copyandexecute** [comment]
ohje
