### ISSUE TITLE
[Bug]: random fabric error

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#448]
### How to reproduce ?

ich wollte die costmetics öffnen und beckam den error 

Uncaught exception in thread "Render thread"
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.wispforest.owo.ui.util.MountingHelper.inflateWithExpand(MountingHelper.java:35)
	at io.wispforest.owo.ui.container.FlowLayout$Algorithm.lambda$static$2(FlowLayout.java:185)
	at io.wispforest.owo.ui.container.FlowLayout.layout(FlowLayout.java:43)
	at io.wispforest.owo.ui.base.BaseParentComponent.inflate(BaseParentComponent.java:164)
	at io.wispforest.owo.ui.base.BaseParentComponent.updateLayout(BaseParentComponent.java:179)
	at io.wispforest.owo.ui.container.FlowLayout.child(FlowLayout.java:54)
	at gg.norisk.cosmetics.ui.v2.cosmetic.CosmeticListComponentV2.redraw(CosmeticListComponentV2.kt:136)
	at gg.norisk.cosmetics.ui.v2.WardrobeComponentV2.handleChildUpdate(WardrobeComponentV2.kt:228)
	at gg.norisk.cosmetics.ui.v2.WardrobeComponentV2$fetchDiscounts$1$1.invokeSuspend(WardrobeComponentV2.kt:274)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6bfe59a2, Dispatchers.Default]

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
Uncaught exception in thread "Render thread"
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.wispforest.owo.ui.util.MountingHelper.inflateWithExpand(MountingHelper.java:35)
	at io.wispforest.owo.ui.container.FlowLayout$Algorithm.lambda$static$2(FlowLayout.java:185)
	at io.wispforest.owo.ui.container.FlowLayout.layout(FlowLayout.java:43)
	at io.wispforest.owo.ui.base.BaseParentComponent.inflate(BaseParentComponent.java:164)
	at io.wispforest.owo.ui.base.BaseParentComponent.updateLayout(BaseParentComponent.java:179)
	at io.wispforest.owo.ui.container.FlowLayout.child(FlowLayout.java:54)
	at gg.norisk.cosmetics.ui.v2.cosmetic.CosmeticListComponentV2.redraw(CosmeticListComponentV2.kt:136)
	at gg.norisk.cosmetics.ui.v2.WardrobeComponentV2.handleChildUpdate(WardrobeComponentV2.kt:228)
	at gg.norisk.cosmetics.ui.v2.WardrobeComponentV2$fetchDiscounts$1$1.invokeSuspend(WardrobeComponentV2.kt:274)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6bfe59a2, Dispatchers.Default]
```

**Comment by copyandexecute** [comment]
sollte jetzt hoffentlich fixed sein! mit dem nächsten update
