### ISSUE TITLE
[Bug]: Crash when making the window to small

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#454]
### How to reproduce ?

Window so klein wie möglich ziehen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -10 is less than minimum 0.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1414)
	at gg.norisk.ui.components.HudDraggableContainer.updateY(HudDraggableContainer.kt:80)
	at io.wispforest.owo.ui.core.Component.moveTo(Component.java:639)
	at io.wispforest.owo.ui.base.BaseComponent.mount(BaseComponent.java:279)
	at io.wispforest.owo.ui.base.BaseParentComponent.mount(BaseParentComponent.java:147)
	at io.wispforest.owo.ui.container.WrappingParentComponent.layout(WrappingParentComponent.java:42)
	at io.wispforest.owo.ui.base.BaseParentComponent.inflate(BaseParentComponent.java:164)
	at io.wispforest.owo.ui.util.MountingHelper.lambda$inflateWithExpand$0(MountingHelper.java:41)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.wispforest.owo.ui.util.MountingHelper.inflateWithExpand(MountingHelper.java:35)
	at io.wispforest.owo.ui.container.FlowLayout$Algorithm.lambda$static$5(FlowLayout.java:232)
	at io.wispforest.owo.ui.container.FlowLayout.layout(FlowLayout.java:43)
	at io.wispforest.owo.ui.base.BaseParentComponent.inflate(BaseParentComponent.java:164)
	at io.wispforest.owo.ui.util.MountingHelper.lambda$inflateWithExpand$0(MountingHelper.java:41)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.wispforest.owo.ui.util.MountingHelper.inflateWithExpand(MountingHelper.java:35)
	at io.wispforest.owo.ui.container.FlowLayout$Algorithm.lambda$static$5(FlowLayout.java:232)
	at io.wispforest.owo.ui.container.FlowLayout.layout(FlowLayout.java:43)
	at io.wispforest.owo.ui.base.BaseParentComponent.inflate(BaseParentComponent.java:164)
	at io.wispforest.owo.ui.core.OwoUIAdapter.inflateAndMount(OwoUIAdapter.java:103)
	at io.wispforest.owo.ui.core.OwoUIAdapter.moveAndResize(OwoUIAdapter.java:113)
	at io.wispforest.owo.ui.hud.Hud.lambda$static$2(Hud.java:94)
	at io.wispforest.owo.ui.event.WindowResizeCallback.lambda$static$0(WindowResizeCallback.java:12)
	at net.minecraft.class_310.handler$edd000$owo$captureResize(class_310.java:22684)
	at net.minecraft.class_310.method_15993(class_310.java:1415)
	at net.minecraft.class_1041.method_4504(class_1041.java:264)
	at org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.mixinextras$bridge$method_15998$383(class_310.java)
	at net.minecraft.class_310.wrapOperation$dgh000$mcreal$maybeSwapBuffers(class_310.java:15661)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by copyandexecute** [comment]
digga was ein bug

**Comment by copyandexecute** [comment]
fixed auf norisk-dev
