### ISSUE TITLE
Pings rendering crash

### ISSUE THREAD

**Issue by Enderfire-09** [NoRiskClient/issues#503]
### How to reproduce ?

Ich hab das "pings" feature ausprobiert und einen beacon gepingt. Darauf hin ist mein Spiel gecrasht :(
joa keine ahnung woran das liegt, ich hab den crash report hier auch mal reingepackt.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Relevant log output

```shell
https://mclo.gs/xHlPAbx
```

**Comment by BigBrainRobin29** [comment]
Betrifft auch den End Gateway Block (https://discord.com/channels/774271756549619722/1299101283990638703)

**Comment by TimLohrer** [comment]
@Greeenman999 @copyandexecute

**Comment by SirKnubble** [comment]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_31600()" because the return value of "net.minecraft.class_2643.method_10997()" is null

at knot//net.minecraft.class_841.method_22751(class_841.java:22)
at knot//net.minecraft.class_841.method_3569(class_841.java:11)
at knot//io.wispforest.owo.ui.component.BlockComponent.lambda$draw$0(BlockComponent.java:62)
at knot//com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
at knot//io.wispforest.owo.ui.component.BlockComponent.draw(BlockComponent.java:50)
at knot//io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354)
at knot//io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145)
at knot//gg.norisk.friends.pings.PingRenderer.renderPing(PingRenderer.kt:134)
at knot//gg.norisk.friends.pings.PingsModule._init_$lambda$1(PingsModule.kt:98)
at knot//net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
```

**Comment by BigBrainRobin29** [comment]
Es liegt vermutlich daran das beide einen Beacon-Beam rendern, welcher zum rendern als Parameter die gameTime verwendet und deshalb die World braucht, welche bei den Pings wahrscheinlich nicht angegeben ist.

**Comment by copyandexecute** [comment]
Bin dran

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/18214c99-8c5f-4243-ae31-53286db6b835)
der fixende boss, kommt im nächsten update

**Comment by TimLohrer** [comment]
Macher!

**Comment by BigBrainRobin29** [comment]
Der Fix ist noch nicht drin, oder?
