### ISSUE TITLE
[Bug]: Crash after Pong win

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#551]
### How to reproduce ?

Wenn man Pong im 2D-Modus gewinnt, crashed das Game

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-11-12 18:24:36
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "io.wispforest.owo.ui.core.ParentComponent.removeChild(io.wispforest.owo.ui.core.Component)" because the return value of "io.wispforest.owo.ui.core.Component.parent()" is null
	at knot//io.wispforest.owo.ui.core.Component.lambda$remove$0(Component.java:317)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at knot//io.wispforest.owo.ui.base.BaseParentComponent.update(BaseParentComponent.java:49)
	at knot//io.wispforest.owo.ui.core.ParentComponent.update(ParentComponent.java:202)
	at knot//io.wispforest.owo.ui.base.BaseParentComponent.update(BaseParentComponent.java:44)
	at knot//io.wispforest.owo.ui.core.OwoUIAdapter.method_25394(OwoUIAdapter.java:172)
	at knot//net.minecraft.class_437.method_25394(class_437.java:128)
	at knot//io.wispforest.owo.ui.base.BaseOwoScreen.method_25394(BaseOwoScreen.java:116)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$298(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bgl000$fabric-screen-api-v1$onRenderScreen(class_757.java:4086)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//io.wispforest.owo.ui.core.Component.lambda$remove$0(Component.java:317)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at knot//io.wispforest.owo.ui.base.BaseParentComponent.update(BaseParentComponent.java:49)
	at knot//io.wispforest.owo.ui.core.ParentComponent.update(ParentComponent.java:202)
	at knot//io.wispforest.owo.ui.base.BaseParentComponent.update(BaseParentComponent.java:44)
	at knot//io.wispforest.owo.ui.core.OwoUIAdapter.method_25394(OwoUIAdapter.java:172)
	at knot//net.minecraft.class_437.method_25394(class_437.java:128)
	at knot//io.wispforest.owo.ui.base.BaseOwoScreen.method_25394(BaseOwoScreen.java:116)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$298(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bgl000$fabric-screen-api-v1$onRenderScreen(class_757.java:4086)

-- Screen render details --
Details:
	Screen name: gg.norisk.minigames.owo.screen.MinigamesScreen
	Mouse location: Scaled: (319, 170). Absolute: (1279.000000, 679.000000)
	Screen size: Scaled: (640, 341). Absolute: (2560, 1361). Scale factor of 4.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 161.696s
	Wall uptime: 122.980s
	High-res time: 108.354s
	Client ticks: 1713 ticks / 85.650s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:902)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 4 total; [class_746['TigerCrafter'/1599, l='ClientLevel', x=-0.20, y=63.00, z=-7.34], class_745['Aim_shock'/1586, l='ClientLevel', x=6.16, y=63.00, z=0.66], class_745['einHopala'/1598, l='ClientLevel', x=0.50, y=64.00, z=0.50], class_745['DasRiRa'/1600, l='ClientLevel', x=10.05, y=64.00, z=-4.99]]
	Chunk stats: 1024, 453 F: 1231 L: 0 U: 83 C: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,100,0), Section: (at 0,4,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 58806325 game time, 6000 day time
	Server brand: fabric (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 6

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, aang, adventure-platform-fabric, armorstands, axiom, bobby, claimpoints, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, datatracker, emote-lib, enchantments, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-gametest-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, ffa-client, ffa-common, freecam, hero-api, hglabor_lobby, hglobbycommon, indium, iris, lithium, mcreal, mm, modernfix, modmenu, morechathistory, net_raphimc_viaaprilfools-common, net_raphimc_viabedrock, net_raphimc_vialegacy, noriskclient, noriskclient-branding, noriskclient-clearbackground, noriskclient-cosmetics, noriskclient-discordintegration, noriskclient-fabric-utils, noriskclient-freelook, noriskclient-fullbright, noriskclient-nametags, noriskclient-nofog, noriskclient-screenshot, noriskclient-toasts, noriskclient-ui, noriskclient-zoom, nrcfriends, nrcminigames, nvidium, owo, owoplus, playeranimator, quests, replaymod, satin, shulkerboxtooltip, silk-all, skinlayers3d, sodium, subwaysurfers, viafabricplus, visiblebarriers, voicechat, xaerominimap, xaeroworldmap, xaerozoomout, file/nrc-cosmetics, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 566988368 bytes (540 MiB) / 1543503872 bytes (1472 MiB) up to 6845104128 bytes (6528 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6603
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MiB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MiB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MiB): 28616.50
	Virtual memory used (MiB): 16096.20
	Swap memory total (MiB): 12288.00
	Swap memory used (MiB): 494.73
	Space in storage for jna.tmpdir (MiB): available: 258675.16, total: 524060.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 258675.16, total: 524060.00
	Space in storage for io.netty.native.workdir (MiB): available: 258675.16, total: 524060.00
	Space in storage for java.io.tmpdir (MiB): available: 258675.16, total: 524060.00
	Space in storage for workdir (MiB): available: 258675.16, total: 524060.00
	JVM Flags: 8 total; -Xmx6505M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		aang: Aang 1.21-1.0.18
		armorstands: Armor Stands 2.0.0
		axiom: Axiom 4.2.0
			com_moulberry_axiomclientapi_axiomclientapi_: axiomclientapi 1.0.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		bobby: Bobby 5.2.4+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		claimpoints: ClaimPoints 2.0.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		datatracker: DataTracker 1.21-1.0.7
		emote-lib: Emote Lib 1.21-1.0.29
		enchantments: Stupid Enchanments 1.21-1.0.7
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.0.0
		ffa-client: FFA Client 1.21-1.1.6
			com_thedeanda_lorem: lorem 2.2
		ffa-common: FFA-Common 1.21-1.0.2
		freecam: Freecam 1.3.0+mc1.21
		geckolib: GeckoLib 4 4.5.7
		hero-api: Hero-Api 1.21-1.1.13
		hglabor_lobby: HGLabor Lobby-Client 1.21-0.0.4
			adventure-platform-fabric: adventure-platform-fabric 5.14.1
				net_kyori_adventure-api: adventure-api 4.17.0
				net_kyori_adventure-key: adventure-key 4.17.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.3
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.17.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.17.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.17.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.17.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.17.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.17.0
				net_kyori_ansi: ansi 1.1.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
				net_kyori_option: option 1.0.0
			de_hglabor_core: core **.**.**.**
			hglobbycommon: HGLabor Lobby Common 1.21-0.0.2
		indium: Indium 1.0.35+mc1.21
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.12.7
		mcreal: McReal 1.21-2.0.34
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.19.1+mc1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		morechathistory: More Chat History 1.3.1
		mousetweaks: Mouse Tweaks 2.26
		noriskclient: NoRisk Client 1.21-2.0.17
			io_airlift_aircompressor: aircompressor 2.0.2
			mm: Manningham Mills 2.3
			org_apache_commons_commons-text: commons-text 1.12.0
		noriskclient-branding: NoRiskClient Branding 1.21-2.0.16
		noriskclient-clearbackground: NoRiskClient ClearBackground 1.21-2.0.0
		noriskclient-cosmetics: NoRiskClient Cosmetics 1.21-2.1.50
		noriskclient-discordintegration: NoRiskClient Discord 1.21-2.0.1
			com_github_caoimhebyrne_kdiscordipc: KDiscordIPC 384357c3f1
			com_kohlschutter_junixsocket_junixsocket-common: junixsocket-common 2.5.0
			com_kohlschutter_junixsocket_junixsocket-native-common: junixsocket-native-common 2.5.0
			org_slf4j_slf4j-api: slf4j-api 1.7.36
		noriskclient-fabric-utils: NoRiskClient Fabric Utils 1.21-2.1.49
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			com_google_errorprone_error_prone_annotations: error_prone_annotations 2.21.1
			com_squareup_okhttp3_okhttp: okhttp 4.10.0
			com_squareup_okio_okio-jvm: okio-jvm 3.0.0
			commons-codec_commons-codec: commons-codec 1.15
			fabric-gametest-api-v1: Fabric Game Test API (v1) 2.0.0+6fc22b998b
			gg_norisk_backend-base-api: backend-base-api 1.2.84
			io_github_darkxanter_webp-imageio: webp-imageio 0.3.2
			io_ktor_ktor-client-cio-jvm: ktor-client-cio-jvm 2.3.1
			io_ktor_ktor-client-content-negotiation-jvm: ktor-client-content-negotiation-jvm 2.3.1
			io_ktor_ktor-client-core-jvm: ktor-client-core-jvm 2.3.1
			io_ktor_ktor-events-jvm: ktor-events-jvm 2.3.1
			io_ktor_ktor-http-cio-jvm: ktor-http-cio-jvm 2.3.1
			io_ktor_ktor-http-jvm: ktor-http-jvm 2.3.1
			io_ktor_ktor-io-jvm: ktor-io-jvm 2.3.1
			io_ktor_ktor-network-jvm: ktor-network-jvm 2.3.1
			io_ktor_ktor-network-tls-jvm: ktor-network-tls-jvm 2.3.1
			io_ktor_ktor-serialization-jvm: ktor-serialization-jvm 2.3.1
			io_ktor_ktor-serialization-kotlinx-json-jvm: ktor-serialization-kotlinx-json-jvm 2.3.1
			io_ktor_ktor-serialization-kotlinx-jvm: ktor-serialization-kotlinx-jvm 2.3.1
			io_ktor_ktor-utils-jvm: ktor-utils-jvm 2.3.1
			io_ktor_ktor-websocket-serialization-jvm: ktor-websocket-serialization-jvm 2.3.1
			io_ktor_ktor-websockets-jvm: ktor-websockets-jvm 2.3.1
			org_checkerframework_checker-qual: checker-qual 3.37.0
			org_mongodb_bson: bson 5.2.0
			org_mongodb_bson-kotlinx: bson-kotlinx 5.2.0
			org_sejda_imageio_webp-imageio: webp-imageio 0.1.6
		noriskclient-freelook: NoRiskClient Freelook 1.21-2.0.2
		noriskclient-fullbright: NoRiskClient Fullbright 1.21-2.0.0
		noriskclient-nametags: NoRiskClient NameTags 1.21-2.0.0
		noriskclient-nofog: NoRiskClient NoFog 1.21-2.0.2
		noriskclient-screenshot: NoRiskClient Screenshot 1.21-2.0.7
		noriskclient-toasts: NoRiskClient Toasts 1.21-2.0.5
		noriskclient-ui: NoRiskClient UI 1.21-2.2.27
		noriskclient-zoom: NoRiskClient Zoom 1.21-2.0.3
		nrcfriends: NoRisk Friends 1.21-2.2.34
			io_jsonwebtoken_jjwt-orgjson: jjwt-orgjson 0.12.5
			org_json_json: json 20231013
		nrcminigames: NoRisk Minigames 1.21-2.0.106
		nvidium: Nvidium 0.2.9-beta
		owo: oωo 0.12.10+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.0
			io_wispforest_endec_gson: gson 0.1.0
			io_wispforest_endec_jankson: jankson 0.1.0
			io_wispforest_endec_netty: netty 0.1.0
		owoplus: OwOPlus 1.21-1.0.9
		playeranimator: Player Animator 1.0.2-rc1+1.21
		quests: Quests 1.21-1.0.15
		replaymod: Replay Mod 1.21-2.6.19
		satin: Satin 2.0.0
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21
		silk-all: Silk (All modules) 1.10.7
			silk-commands: Silk Commands 1.10.7
			silk-core: Silk Core 1.10.7
			silk-game: Silk Game 1.10.7
			silk-igui: Silk Inventory GUI 1.10.7
			silk-nbt: Silk NBT 1.10.7
			silk-network: Silk Network 1.10.7
			silk-persistence: Silk Persistence 1.10.7
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sodium: Sodium 0.5.11+mc1.21
		subwaysurfers: SubwaySurfers 1.21-2.2.30
			gg_norisk_subwaysurfers-api: subwaysurfers-api 1.21-1.0.0
		viafabricplus: ViaFabricPlus 3.4.8
			com_github_oryxel_cubeconverter: CubeConverter 5ae1e90e4f
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.0.4-20240925.151321-23
			com_viaversion_viaversion-common: viaversion-common 5.0.4-20240924.171214-42
			de_florianmichael_classic4j: Classic4J 2.1.1-SNAPSHOT
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.6
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.6
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.6
			io_netty_netty-codec-http: netty-codec-http 4.1.113
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.6.0
			net_lenni0451_mcping: MCPing 1.4.1
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.1
			net_lenni0451_mcstructs-bedrock_text: text 1.2.1
			net_lenni0451_reflect: Reflect 1.3.4
			net_raphimc_minecraftauth: MinecraftAuth 4.1.1
			net_raphimc_viaaprilfools-common: viaaprilfools-common 3.0.2-20240916.221413-11
			net_raphimc_viabedrock: ViaBedrock 0.0.12-20240923.200235-5
			net_raphimc_vialegacy: ViaLegacy 3.0.3-20240924.191315-25
			net_raphimc_vialoader: ViaLoader 3.0.3-20240924.155213-19
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
		visiblebarriers: Visible Barriers 2.0.16
		voicechat: Simple Voice Chat 1.21.1-2.5.24
		xaerominimap: Xaero's Minimap 24.5.0
		xaeroworldmap: Xaero's World Map 1.39.0
		xaerozoomout: XaeroZoomout 2.0.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.16.9-1.21
	Launcher name: NoRiskClient
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.03, NVIDIA Corporation
	Window size: 2560x1361
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to '§bnorisk:1.21-2.0.17§r'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 20/20 chunks
	Resource Packs: vanilla, fabric, aang, adventure-platform-fabric, armorstands, axiom, bobby, claimpoints (incompatible), cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, datatracker, emote-lib, enchantments, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-gametest-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, ffa-client, ffa-common, freecam, hero-api, hglabor_lobby, hglobbycommon, indium, iris, lithium, mcreal, mm, modernfix (incompatible), modmenu, morechathistory, net_raphimc_viaaprilfools-common, net_raphimc_viabedrock, net_raphimc_vialegacy, noriskclient, noriskclient-branding, noriskclient-clearbackground, noriskclient-cosmetics, noriskclient-discordintegration, noriskclient-fabric-utils, noriskclient-freelook, noriskclient-fullbright, noriskclient-nametags, noriskclient-nofog, noriskclient-screenshot, noriskclient-toasts, noriskclient-ui, noriskclient-zoom, nrcfriends, nrcminigames, nvidium, owo, owoplus, playeranimator, quests, replaymod (incompatible), satin, shulkerboxtooltip, silk-all, skinlayers3d, sodium, subwaysurfers, viafabricplus, visiblebarriers, voicechat, xaerominimap (incompatible), xaeroworldmap (incompatible), xaerozoomout (incompatible), file/nrc-cosmetics (incompatible)
	Current Language: en_us
	Locale: de_AT
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 4x Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
```

**Comment by TigerCrafter** [comment]
Liegt an Xaeros Minimap

**Comment by TigerCrafter** [comment]
Liegt anscheinend doch nicht an Xaeros Minimap

**Comment by copyandexecute** [comment]
fixed mit nächsten update (hoffentlich) gerne wieder aufmachen sonst
