### ISSUE TITLE
[Bug]: MCReal crash

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#575]
### How to reproduce ?

https://discord.com/channels/774271756549619722/1308068816214822953 Es crasht beim öffnen des MCReal Fensters.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
[15:24:51] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at knot/net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NullPointerException
	at knot/gg.norisk.utils.Shaders.getOrCreateLayer$lambda$2$lambda$0(Shaders.kt:87) ~[NoRiskClient-Fabric-Utils.jar:?]
	at knot/net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at knot/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1109) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1921.method_60895(class_1921.java:894) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_60893(class_4597.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_22994(class_4597.java:85) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_37104(class_4597.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_22993(class_4597.java:75) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51452(class_332.java:130) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51741(class_332.java:93) ~[client-intermediary.jar:?]
	at knot/gg.norisk.ui.components.ScalableLabelComponent.draw(ScalableLabelComponent.kt:46) ~[owoplus.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib.jar:?]
	at knot/gg.norisk.ui.components.LoadingComponent.draw(LoadingComponent.kt:37) ~[NoRiskClient-UI.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.container.ScrollContainer.draw(ScrollContainer.java:127) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib.jar:?]
	at knot/io.wispforest.owo.ui.core.OwoUIAdapter.method_25394(OwoUIAdapter.java:178) ~[owo-lib.jar:?]
	at knot/net.minecraft.class_437.method_25394(class_437.java:128) ~[client-intermediary.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseOwoScreen.method_25394(BaseOwoScreen.java:116) ~[owo-lib.jar:?]
	at knot/net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$method_47413$259(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$bbp000$fabric-screen-api-v1$onRenderScreen(class_757.java:3086) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by Flytzer** [comment]
Bitte das nächste mal mit https://mclo.gs/ schicken

**Comment by BigBrainRobin29** [comment]
> Bitte das nächste mal mit [mclo.gs](https://mclo.gs/) schicken

Das ist vom DC und außerdem habe ich das (meines Wissens nach) Relevante schon rausgesucht. Generell ist mclogs natürlich praktischer.

**Comment by Flytzer** [comment]
Ja deswegen sag ich

**Comment by Flytzer** [comment]
war nich böse gemeint. ^^

**Comment by BigBrainRobin29** [comment]
Ich halte es halt nicht für sinnvoll die paar Zeilen noch da hochzuladen, wenn man hier sowieso ein Feld dafür hat.

**Comment by copyandexecute** [comment]
Noch Valid? und wenn ja wie reproduzieren

**Comment by BigBrainRobin29** [comment]
https://discord.com/channels/774271756549619722/1308068816214822953/1314176020890255391 ist noch valid, aber kp wie reproduzieren, bei ihm crasht es einfach wenn er den mcreal screen öffnet, liegt wahrscheinlich an den text shaders. woran es liegt kannst du besser rausfinden als ich, hab den source code ja nd

**Comment by 0x3C50** [comment]
liegt definitiv an den text shaders. ohne weitere logs können wir da aber nicht viel machen

**Comment by 0x3C50** [comment]
Relevant im log:
```
[15:22:24] [Render thread/WARN]: Error encountered when linking program containing VS noriskclient-fabric-utils:nrc_rendertype_text and FS noriskclient-fabric-utils:nrc_rendertype_text. Log output:
[15:22:24] [Render thread/WARN]: Vertex shader(s) failed to link.
Vertex link error: HW_UNSUPPORTED.
ERROR: Internal compile error, error code: E_SC_LITERAL_NOT_DEFINED
Shader not supported by HW
```

**Comment by TimLohrer** [comment]
@0x3C50 braucht ihr immernoch logs oder könnte man das hier mal anschauen?

**Comment by 0x3C50** [comment]
wahrscheinlich hardware bedingt. treiber aktualisieren? gpu austauschen?
