### ISSUE TITLE
[Bug]: Weird crash while playing tictactoe/pong

### ISSUE THREAD

**Issue by Krxwallo** [NoRiskClient/issues#66]
### What happened?

Relevant method: `net.minecraft.util.math.random.CheckedRandom#next`

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-12-23 16:48:17
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.thread.LockHelper.crash(LockHelper.java:79)
	at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom.java:44)
	at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:19)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld.java:374)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld.java:353)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1948)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1208)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:818)
	at net.minecraft.client.main.Main.main(Main.java:243)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.thread.LockHelper.crash(LockHelper.java:79)
	at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom.java:44)
	at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:19)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld.java:374)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld.java:353)

-- Thread dumps --
Details:
	Thread dumps: Render thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.thread.LockHelper.formatStackTraceForThread(LockHelper.java:87)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.util.thread.LockHelper.crash(LockHelper.java:74)
	at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom.java:44)
	at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:19)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld.java:374)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld.java:353)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1948)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1208)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:818)
	at net.minecraft.client.main.Main.main(Main.java:243)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Stacktrace:
	at net.minecraft.util.thread.LockHelper.crash(LockHelper.java:79)
	at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom.java:44)
	at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:19)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld.java:374)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld.java:353)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1948)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1208)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:818)
	at net.minecraft.client.main.Main.main(Main.java:243)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Uptime --
Details:
	JVM uptime: 232.706s
	Wall uptime: 219.758s
	High-res time: 217.668s
	Client ticks: 4139 ticks / 206.950s
Stacktrace:
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2441)
	at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:929)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:836)
	at net.minecraft.client.main.Main.main(Main.java:243)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['NQRMAN'/204, l='ClientLevel', x=-33.52, y=63.00, z=40.73]]
	Chunk stats: 225, 109
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,48), Section: (at 0,0,0 in 0,4,3; chunk contains blocks 0,-64,48 to 15,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 91561 game time, 91561 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 86

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2914421872 bytes (2779 MiB) / 4555014144 bytes (4344 MiB) up to 8535408640 bytes (8140 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13500
	Identifier: Intel64 Family 6 Model 191 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x4680
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4889
	Graphics card #1 name: AMD Radeon RX 6600
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x73ff
	Graphics card #1 versionInfo: DriverVersion=31.0.21024.3006
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 48499.61
	Virtual memory used (MB): 43366.81
	Swap memory total (MB): 15955.49
	Swap memory used (MB): 1814.11
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric-api: Fabric API 0.91.3+1.20.4
		fabric-api-base: Fabric API Base 0.4.35+78d798af4f
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
		fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
		fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
		fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
		fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
		fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
		fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.14+78d798af4f
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.19+78d798af4f
		fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.16+kotlin.1.9.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
		fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
		fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
		fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
		fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.7+78d798af4f
		fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
		fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
		fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.3
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		mixinextras: MixinExtras 0.3.2
		noriskclient-fabric-utils: Example Mod 1.0.8-SNAPSHOT
		nrcfriends: NoRisk Friends 1.0.5
		nrcminigames: NoRisk Minigames 1.0.8
		silk-commands: Silk Commands 1.10.3
		silk-core: Silk Core 1.10.3
		silk-igui: Silk Inventory GUI 1.10.3
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: AMD Radeon RX 6600 GL version 3.2.0 Core Profile Context 23.10.24.03.230811, ATI Technologies Inc.
	Window size: 1278x664
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 4/4 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: de_DE
	CPU: 20x 13th Gen Intel(R) Core(TM) i5-13500
	Server Running: true
	Player Count: 1 / 8; [ServerPlayerEntity['NQRMAN'/204, l='ServerLevel[New World]', x=-33.52, y=63.00, z=40.73]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

**Comment by copyandexecute** [comment]
Das sollte es fixen mal gucken ob es wieder auftritt
