### ISSUE TITLE
[Bug]: Piston Ping Crash (1.21.4)

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#683]
### How to reproduce ?

Piston pingen und crash.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
https://mclo.gs/fO9Js7E
```

**Comment by BigBrainRobin29** [comment]
Crasht, weil die direction/facing null ist, aber das zum rendern des heads benötigt wird.

**Comment by BigBrainRobin29** [comment]
Crasht in 1.21.4 wieder (reportet by crafterpaul in [#bugs](https://discord.com/channels/774271756549619722/1337780650291367937))

https://mclo.gs/ZfwJVtJ

```
java.lang.IllegalStateException: Invalid block entity minecraft:piston // net.minecraft.class_2669 state at class_2338{x=0, y=-59, z=12}, got Block{minecraft:piston}[extended=false,facing=north]
at knot//net.minecraft.class_2586.method_61175(class_2586.java:56)
at knot//net.minecraft.class_2586.<init>(class_2586.java:50)
at knot//net.minecraft.class_2669.<init>(class_2669.java:52)
at knot//net.minecraft.class_2591.method_11032(class_2591.java:110)
at knot//gg.norisk.friends.pings.PingRenderer.renderPing(PingRenderer.kt:110)
```

**Comment by copyandexecute** [comment]
![Image](https://github.com/user-attachments/assets/27d3a8cd-56a8-465c-bc69-7fb5faa8242d)
